baseURL = "http://localhost:1313"
title = "Red Team Village"
author = "Red Team Village"
languageCode = "en"
DefaultContentLanguage = "en"
enableInlineShortcodes = true
theme = "Blonde"
enableRobotsTXT = true

# Please enable this feature if the site is available in Japanese, Chinese or Korean.
#hasCJKLanguage = true

# If you're using Google Analytics, you can enable this feature.
#googleAnalytics = "G-1234567890"

# Disqus Comment System
#disqusShortname = ""

[params]
# Base color of the website.
# https://tailwindcss.com/docs/background-color
base_color = "bg-neutral-800"

  customHeadHTML = '''
    <link rel="stylesheet" href="https://cdnjs.cloudflare.com/ajax/libs/font-awesome/6.5.1/css/all.min.css">
  '''
  
#Site description
description = "Red Team Village"

# The number of articles to be displayed on a single page.
paginator_pages = "5"

# Enable this if you want the archive list to be in a drop-down format.
archive_dropdown = "false"

# Number of tags to be displayed.
tagsLimit = 20

# Always use dark mode
darkmode = "dark"

  [params.ad]
    # Google AdSense
    # ex. ca-pub-0000000000000000
    googleAdSense = ""

    # ex. 000000000
    adslot = ""

    # Placement of ads
    postTop = false
    postBottom = false

  [params.post]
    # Show thumbnails
    thumbnail = true

    # Disable the "NO IMAGE" image.
    noimage = true

    # See the Tailwind CSS documentation to set it up.
    # Recommended settings are h-32 to h-48.
    # https://tailwindcss.com/docs/height
    thumbnail_height = "lg:h-44"

    # https://tailwindcss.com/docs/width
    thumbnail_width = "lg:w-auto"

    # Number of characters in description
    description = "130"
  [params.widgets]
    # Display widgets
    display = true

    # Order of widgets to display
    widgets = ["search", "archive", "category", "tags", "recent"]

# If you're using Yandex.Metrica, you can enable this feature.
#[params.analytics.yandexmetrica]
#    enabled = true
#    tagNumber = ''

[menu]

  [[menu.main]]
    identifier = "logo"
    name = ""  # Empty name since we're using an image
    url = "/"
    weight = 0
    pre = "<img src='assets/images/rtv-logo.png' alt='RTV Logo' style='height: 40px; width: auto;'>"

  [[menu.main]]
    identifier = "rtv-team"
    name = "<i class='fas fa-users'></i> TEAM"
    url = "/team/"
    weight = 1

  [[menu.main]]
    identifier = "venue"
    name = "<i class='fas fa-map-marker-alt'></i> VENUE"
    url = "/venue/"
    weight = 2

  [[menu.main]]
    identifier = "schedule"
    name = "<i class='far fa-calendar'></i> SCHEDULE"
    url = "/schedule/"
    weight = 3

  [[menu.main]]
    identifier = "discord"
    name = "<i class='fab fa-discord'></i> DISCORD"
    url = "https://discord.gg/redteamvillage"
    weight = 4
    target = "_blank"

  [[menu.main]]
    identifier = "twitter"
    name = "<i class='fab fa-twitter'></i> TWITTER"
    url = "https://x.com/redteamvillage_"
    weight = 5
    target = "_blank"

  [[menu.main]]
    identifier = "youtube"
    name = "<i class='fab fa-youtube'></i> YOUTUBE"
    url = "https://www.youtube.com/redteamvillage"
    weight = 6
    target = "_blank"

  [[menu.main]]
    identifier = "volunteer"
    name = "<i class='fas fa-external-link-alt'></i> VOLUNTEER PORTAL"
    url = "https://volunteer.redteamvillage.io"
    weight = 7
    target = "_blank"

  # Footer Social Icons
  [[menu.footer]]
    identifier = "discord"
    name = "<i class='fab fa-discord fa-lg'></i>"
    url = "https://discord.gg/redteamvillage"
    weight = 1
    target = "_blank"

  [[menu.footer]]
    identifier = "twitter"
    name = "<i class='fab fa-twitter fa-lg'></i>"
    url = "https://x.com/redteamvillage_"
    weight = 2
    target = "_blank"

  [[menu.footer]]
    identifier = "youtube"
    name = "<i class='fab fa-youtube fa-lg'></i>"
    url = "https://www.youtube.com/redteamvillage"
    weight = 3
    target = "_blank"

[taxonomies]
category = "categories"
tag = "tags"
archive = "archives"

[privacy]

  [privacy.vimeo]
    disabled = false
    simple = true

  [privacy.twitter]
    disabled = false
    enableDNT = true
    simple = true

  [privacy.instagram]
    disabled = false
    simple = true

  [privacy.youtube]
    disabled = false
    privacyEnhanced = true

[services]

  [services.instagram]
    disableInlineCSS = true

  [services.twitter]
    disableInlineCSS = true

[params.team]
  [[params.team.members]]
    name = "Mike Lisi"
    handle = "@mikehacksthings"
    role = "President"
    image = "mike-240x240.png"
    linkedin = "https://www.linkedin.com/in/mikelisi/"
    twitter = "https://x.com/mikehacksthings"

  [[params.team.members]]
    name = "Danielle Sink"
    handle = "@ds1nk"
    role = "Vice President"
    image = "dsink-240x240.jpg"
    linkedin = "https://www.linkedin.com/in/dssink/"
    twitter = "https://x.com/ds1nk"

  [[params.team.members]]
    name = "Billy Giles"
    handle = "@forktheplanet"
    role = "Treasurer"
    image = "billy-240x240.jpg"
    linkedin = "https://www.linkedin.com/in/wrgiles/"
    twitter = "https://x.com/forktheplanet"

  [[params.team.members]]
    name = "Bryce Zuccharo"
    handle = "@c4ch3c4d3"
    role = "Secretary"
    image = "bryce-240x240.jpg"
    linkedin = "https://www.linkedin.com/in/brycezuccaro/"
    twitter = "https://x.com/c4ch3c4d3"

  [[params.team.members]]
    name = "Cory Wolff"
    handle = "@cwolff411"
    role = "Director of Workshops"
    image = "cory-240x240.jpg"
    linkedin = "https://www.linkedin.com/in/corywolff/"
    twitter = "https://x.com/cwolff411"

  [[params.team.members]]
    name = "Krista Theodore"
    handle = "@InfoSecOprah"
    role = "Director of Marketing"
    image = "krista-240x240.jpg"
    linkedin = "https://www.linkedin.com/in/kristamtheodore/"
    twitter = "https://x.com/@InfoSecOprah"

  [[params.team.members]]
    name = "Brian Sak"
    handle = "@briansak"
    role = "Director of Logistics"
    image = "brian-240x240.jpg"
    linkedin = "https://www.linkedin.com/in/briansak/"
    twitter = "https://x.com/@briansak"

  [[params.team.members]]
    name = "Filipi Peres"
    handle = "@FilipiPires"
    role = "Director of Sponsors"
    image = "filipi-240x240.jpg"
    linkedin = "https://www.linkedin.com/in/filipipires/"
    twitter = "https://x.com/@FilipiPires"

  [[params.team.members]]
    name = "Michael Donley"
    handle = "@th3d00rman"
    role = "Director of Volunteers"
    image = "michael-240x240.jpg"
    linkedin = "https://www.linkedin.com/in/michael-donley-red-team-pentester-educator/"
    twitter = "https://x.com/@th3d00rman"

  [[params.team.members]]
    name = "Troy Fridley"
    handle = ""
    role = "Core Staff"
    image = "troy-240x240.jpg"
    linkedin = "https://www.linkedin.com/in/troy-fridley-54a9252/"
    twitter = "https://x.com/@th3d00rman"

  [[params.team.members]]
    name = "Nate Sanders"
    handle = "@mauvehead"
    role = "Core Staff"
    image = "nate-240x240.jpg"
    linkedin = "https://www.linkedin.com/in/sandersn/"

  [[params.team.members]]
    name = "Greg Oldham"
    handle = "@Hax4Coffee"
    role = "Core Staff"
    image = "greg-240x240.jpg"
    linkedin = "https://www.linkedin.com/in/greg-oldham-cfis/"
    twitter = "https://x.com/@hax4coffee"

  [[params.team.members]]
    name = "Austin Cundiff"
    handle = "@sysdum"
    role = "Core Staff"
    image = "austin-240x240.jpg"
    linkedin = "https://www.linkedin.com/in/austin-cundiff-7b015811a/"
    twitter = "https://x.com/@sysdum"

  [[params.team.members]]
    name = "Jon Kim"
    handle = "@j0nk1m"
    role = "Core Staff"
    image = "jon-240x240.jpg"
    linkedin = "https://www.linkedin.com/in/jonathanskim/"
    twitter = "https://x.com/@j0nk1m"

  [[params.team.members]]
    name = "Omar Santos"
    handle = "@Î©r"
    role = "Village Advisor"
    image = "omar-240x240.jpg"
    linkedin = "https://www.linkedin.com/in/santosomar/"
    twitter = "https://x.com/santosomar"

  [[params.team.members]]
    name = "Barrett Darnell"
    handle = "@pwneip"
    role = "Village Advisor"
    image = "barret-240x240.jpg"
    linkedin = "https://www.linkedin.com/in/barrettdarnell/"
    twitter = "https://x.com/pwneip"

  [[params.team.members]]
    name = "Savannah Lazzara"
    handle = "@lazzslayer"
    role = "Village Advisor"
    image = "savannah-240x240.jpg"
    linkedin = "https://www.linkedin.com/in/savannahlazzara/"
    twitter = "https://x.com/lazzslayer"

  [[params.team.members]]
    name = "Wes Thurner"
    handle = "@nopresearcher"
    role = "Village Advisor"
    image = "wes-240x240.jpg"
    linkedin = "https://www.linkedin.com/in/wesleythurner/"
    twitter = "https://x.com/nopresearcher"
